blogs/urls.py
from django.urls import path
from .views import (CategoryListView, ArticlesListView, ArticlesUpdateView,
                    ArticlesDetailView, ArticlesCreateView, SearchView, LikeArticleView,
                    WatchLaterArticleView, WatchLaterArticlesView, LikedArticlesView,
                    AddReviewsView, ReviewsDetailView, UnlikeArticleView, RemoveWatchLaterView,
                    ArticlesDeleteView)

app_name = 'blogs'
urlpatterns = [
    path('category-list', CategoryListView.as_view(), name='category-list'),
    path('articles-list/<int:pk>/', ArticlesListView.as_view(), name='articles-list'),
    path('articles-detail/<int:pk>/', ArticlesDetailView.as_view(), name='articles-detail'),
    path('articles/<int:pk>/update/', ArticlesUpdateView.as_view(), name='articles-update'),
    path('articles-add/', ArticlesCreateView.as_view(), name='articles-add'),
    path('search/', SearchView.as_view(), name='search'),
    path('articles/<int:pk>/like/', LikeArticleView.as_view(), name='articles-like'),
    path('articles/<int:pk>/watch-later/', WatchLaterArticleView.as_view(), name='articles-watch-later'),
    path('liked-articles/', LikedArticlesView.as_view(), name='liked-articles'),
    path('watch-later-articles/', WatchLaterArticlesView.as_view(), name='watch-later-articles'),
    path('add_review/<int:pk>/', AddReviewsView.as_view(), name='add-review'),
    path('reviews-detail/<int:pk>/', ReviewsDetailView.as_view(), name='review-detail'),
    path('unlike/<int:pk>/articles', UnlikeArticleView.as_view(), name='unlike-articles'),
    path('remove/<int:pk>/watch-later', RemoveWatchLaterView.as_view(), name='remove-watch-later'),
    path('delete/<int:pk>/article/', ArticlesDeleteView.as_view(), name='delete-article')

]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('blogs/', include('blogs.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models
from users.models import CustomUser
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.name


class Articles(models.Model):
    title = models.CharField(max_length=256, blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    star_given = models.IntegerField(
        default=0,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(5)
        ]
    )
    image = models.ImageField(upload_to='article_images/', blank=True, null=True,
                              default='default_images/not_available.png')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'articles'

    def __str__(self):
        return f'{self.category.name} - {self.title}'


class UserArticleInteraction(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)
    watch_later = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'article')


class Reviews(models.Model):
    comment = models.TextField()
    star_given = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
    )
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        db_table = 'reviews'

    def __str__(self):
        return f'{self.user} - {self.article}'

blogs/forms.py
from django import forms
from .models import Category, Articles, Reviews


class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ('title', 'text', 'image')


class ReviewsForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('comment', 'star_given')

blogs/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Articles, UserArticleInteraction, Reviews
from django.views import View
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse_lazy
from .forms import ArticlesForm, ReviewsForm
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from users.models import CustomUser
from django.db.models import Q


# Create your views here.


class CategoryListView(View):
    def get(self, request):
        category = Category.objects.all()
        articless = Articles.objects.all()
        context = {
            'category': category,
            'articles': articless
        }
        return render(request, 'blogs/category_list.html', context=context)


class ArticlesListView(View):
    def get(self, request, pk):
        articles = Articles.objects.filter(category=pk)
        context = {
            'articles': articles,
        }
        return render(request, 'blogs/articles_list.html', context=context)


class ArticlesDetailView(View):
    def get(self, request, pk):
        article = Articles.objects.get(pk=pk)
        star_given_review = Reviews.objects.filter(article_id=pk)
        result = [review.star_given for review in star_given_review if 1 < review.star_given < 6]
        average = round(sum(result) / len(result), 1) if result else None
        return render(request, 'blogs/articles_detail.html', {'article': article, 'star_given_review':star_given_review, 'average':average})


class ArticlesUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        if article.author != request.user:
            raise PermissionDenied("You are not allowed to edit this article.")

        update_article_form = ArticlesForm(instance=article)
        context = {
            'update_article_form': update_article_form,
            'article': article
        }
        return render(request, 'blogs/articles_update.html', context=context)

    def post(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        if article.author != request.user:
            raise PermissionDenied("You are not allowed to edit this article.")

        update_article_form = ArticlesForm(request.POST, request.FILES, instance=article)
        if update_article_form.is_valid():
            update_article_form.save()
            messages.success(request, "Article updated successfully!")
            return redirect('blogs:articles-detail', pk=article.pk)
        else:
            context = {
                'update_article_form': update_article_form,
                'article': article
            }
            return render(request, 'blogs/articles_update.html', context=context)

    def get_success_url(self):
        return reverse_lazy('blogs:articles-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Article updated successfully!")
        return response


class ArticlesCreateView(CreateView):
    model = Articles
    template_name = 'blogs/articles_create.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('blogs:articles-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Article added successfully!")
        return response


class SearchView(View):
    def get(self, request):
        query = request.GET.get('q')
        article = Articles.objects.filter(
            Q(Q(title__icontains=query) | Q(author__username__icontains=query))
        )
        context = {
            'articles': article,
            'query': query
        }
        return render(request, 'blogs/search_results.html', context=context)


@method_decorator(login_required, name='dispatch')
class LikeArticleView(View):
    def post(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        interaction, crated = UserArticleInteraction.objects.get_or_create(user=request.user, article=article)
        interaction.liked = not interaction.liked
        messages.success(request,'Added to like')
        interaction.save()
        return redirect('blogs:articles-detail', pk=pk)


@method_decorator(login_required, name='dispatch')
class UnlikeArticleView(View):
    def post(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        interaction = get_object_or_404(UserArticleInteraction, user=request.user, article=article)
        if interaction.liked:
            interaction.liked = False
            interaction.save()
            messages.success(request, 'Removed from Liked Articles')
        return redirect('blogs:liked-articles')

@method_decorator(login_required, name='dispatch')
class WatchLaterArticleView(View):
    def post(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        interaction, created = UserArticleInteraction.objects.get_or_create(user=request.user, article=article)
        interaction.watch_later = not interaction.watch_later
        messages.success(request, 'Added to watch later')
        interaction.save()
        return redirect('blogs:articles-detail', pk=pk)


@method_decorator(login_required, name='dispatch')
class RemoveWatchLaterView(View):
    def post(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        interaction = get_object_or_404(UserArticleInteraction, user=request.user, article=article)
        if interaction.watch_later:
            interaction.watch_later = False
            interaction.save()
            messages.success(request, 'Removed from Watch Later')
        return redirect('blogs:watch-later-articles')


@method_decorator(login_required, name='dispatch')
class LikedArticlesView(View):
    def get(self, request):
        liked_interactions = UserArticleInteraction.objects.filter(user=request.user, liked=True)
        liked_articles = [interaction.article for interaction in liked_interactions]
        context = {
            'liked_articles': liked_articles
        }
        return render(request, 'blogs/liked_articles.html', context=context)

@method_decorator(login_required, name='dispatch')
class WatchLaterArticlesView(View):
    def get(self, request):
        interactions = UserArticleInteraction.objects.filter(user=request.user, watch_later=True)
        articles = [interaction.article for interaction in interactions]
        return render(request, 'blogs/watch_later_articles.html', {'articles': articles})


class AddReviewsView(View):
    def get(self, request, pk):
        articles = Articles.objects.get(pk=pk)
        add_review_form = ReviewsForm()
        context = {
            'articles': articles,
            'add_review_form': add_review_form
        }
        return render(request, 'blogs/add_review.html', context=context)

    def post(self, request, pk):
        articles = Articles.objects.get(pk=pk)
        add_review_form = ReviewsForm(request.POST)
        if add_review_form.is_valid():
            review = Reviews.objects.create(
                comment=add_review_form.cleaned_data['comment'],
                article=articles,
                user=request.user,
                star_given=add_review_form.cleaned_data['star_given']
            )
            review.save()
            messages.success(request, "Review added successfully.")
            return redirect('blogs:articles-detail', pk=pk)
        else:
            messages.error(request, "Failed to add review. Please check the form.")
            return render(request, 'blogs/add_review.html', {'articles': articles, 'add_review_form': add_review_form})

class ReviewsDetailView(View):
    def get(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        reviews = Reviews.objects.filter(article_id=pk)
        context = {
            'article': article,
            'reviews': reviews
        }
        return render(request, 'blogs/reviews_detail.html', context)


class ArticlesDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        if article.author != request.user:
            raise PermissionDenied("You are not allowed to delete this article.")

        context = {
            'article': article
        }
        return render(request, 'blogs/articles_delete.html', context=context)

    def post(self, request, pk):
        article = get_object_or_404(Articles, pk=pk)
        if article.author != request.user:
            raise PermissionDenied("You are not allowed to delete this article.")

        article.delete()
        messages.success(request, "Article deleted successfully!")
        return redirect('blogs:articles-list', pk=pk)

templates/blogs/add_review.html
{% extends 'base.html' %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Add review{% endblock %}</title>
</head>
{% block content %}

<h3>{{ articles.title }}</h3>
<form method="post" >
    {% csrf_token %}
    {{ add_review_form.as_p }}
    <input type="submit" value="Add Review">
</form>

{% endblock content%}

templates/blogs/articles_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Add Article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

templates/blogs/articles_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Article</h1>
    <p>Do you confirm to delete this article "{{ article.title }}" ?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <a href="{% url 'blogs:articles-detail' article.pk %}">Back</a>
    </form>
{% endblock %}

templates/blogs/articles_detail.html
{% extends 'base.html' %}
{% block title %} {{article.title}} {% endblock %}
{%block content %}
    <div class="main_page">
        <div class="article-container ">
            <h1>{{ article.title }}</h1> 
            
            <img src="{{ article.image.url }}" alt="Article Image">
            
            <h4>Written by: {{ article.author }}</h4>
            
            <div class="content">
                <p>{{ article.text }}</p>
            </div>
            <div class="footer">
                <a href="{% url 'blogs:review-detail' article.pk %}">Reviews</a> |
                <a href="{% url 'blogs:add-review' article.pk%}">Add Review</a>
            </div>
            <div class="footer">
                <a href="{% url 'blogs:articles-update' article.pk %}">Edit</a> |
                <a href="{% url 'blogs:articles-add' %}">Add</a> |
                <a href="{% url 'blogs:delete-article' article.pk %}">Delete</a>
            </div>

            <div class="footer">
                <a href="{% url 'blogs:category-list' %}">Back to Categories</a>
            </div>
            
            <div class="interaction-buttons">
                
                <form action="{% url 'blogs:articles-like' pk=article.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Like</button>
                </form>
                
                <form action="{% url 'blogs:articles-watch-later' article.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Watch Later</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/blogs/articles_list.html
{% extends 'base.html' %}

{% block content %}
    {% if articles %}
        <div class="cards">
            {% for a in articles %}
                <div class="card">
                    <img src="{{ a.image.url }}" alt="Not found" class="card-img">
                    <h2>{{a.title}}</h2>
                    <h4>Author:{{a.author}}</h4>
                    <div class="star-rating" data-rating="{{ a.star_given }}">
                        <span class="stars"></span>
                    </div>
                    <a href="{% url 'blogs:articles-detail' a.pk %}"><button>Read More</button></a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No available articles to read now.</p>
        <a href="{% url 'blogs:category-list' %}">Back to Categories</a>
    {% endif %}
{% endblock content %}

templates/blogs/articles_update.html
{extends 'base.html'}
{% block content %}
    <h1>Update Article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_article_form.as_p }}
        <button type="submit">Save changes</button>
    </form>
{% endblock %}

templates/blogs/blogs_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                {% for c in category %}
                    <a href="#">{{ c.name }} | </a>
                {% endfor %}

            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p></p>
    </footer>
</body>
</html>

templates/blogs/category_list.html
{% extends 'base.html' %}

{% block title %} Articles {% endblock %}
{% block content %}
<hr>
<header class="header-nav">
    <nav>
        <ul class="categories-list">
            {% for c in category %}
                <li>
                    <a href="{% url 'blogs:articles-list' c.pk %}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
</header>

<div class="cards">
    {% for a in articles %}
        <div class="card">
            <img src="{{ a.image.url }}" alt="Not found" class="card-img">
            <h2>{{a.title}}</h2>
            <h4>Author: {{a.author}}</h4>
            <div class="star-rating" data-rating="{{ a.star_given }}">
                <span class="stars"></span>
            </div>
            <a href="{% url 'blogs:articles-detail' a.pk %}"><button>Read More</button></a>
        </div>
    {% endfor %}    
</div>



<div class="add-article-container">
    <div class="add-article">
        <a href="{% url 'blogs:articles-add' %}">Add Article</a>
    </div>
</div>
{% endblock content %}

templates/blogs/liked_articles.html
{% extends 'base.html' %}

{% block title %}Liked Articles{% endblock %}

{% block content %}
    {% if liked_articles %}
        <div class="cards">
            {% for a in liked_articles %}
                <div class="card">
                    <img src="{{ a.image.url }}" alt="Not found" class="card-img">
                    <h2>{{a.title}}</h2>
                    <h4>Author:{{a.author}}</h4>
                    <div class="star-rating" data-rating="{{ a.star_given }}">
                        <span class="stars"></span>
                    </div>
                    <a href="{% url 'blogs:articles-detail' a.pk %}"><button>Read More</button></a>
                    <form action="{% url 'blogs:unlike-articles' a.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="unlike-button">Unlike</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No liked articles.</p>
    {% endif %}
{% endblock %}

templates/blogs/reviews_detail.html
{% extends 'base.html' %}
{% block content %}

    {% for r in reviews %}
        <h4>{{ r.user }}</h4>
        <p>{{ r.comment }}</p>
        Star given: {{ r.star_given }}<br><br>
    {% endfor %}
        <a href="{% url 'blogs:articles-detail' article.pk %}">Back</a>
{% endblock %}

templates/blogs/search_results.html
{% extends 'base.html' %}

{% block title %}Search Results{% endblock %}

{% block content %}
  <h1>Search Results for "{{ query }}"</h1>
  {% if articles %}
    <ul>
      {% for article in articles %}
        <li>
          <a href="{% url 'blogs:articles-detail' article.pk %}">{{ article.title }}</a>
          by {{ article.author.username }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No articles found.</p>
  {% endif %}
{% endblock %}

templates/blogs/watch_later_articles.html
{% extends 'base.html' %}

{% block title %}Watch Later Articles{% endblock %}

{% block content %}

    {% if articles %}
        <div class="cards">
            {% for a in articles %}
                <div class="card">
                    <img src="{{ a.image.url }}" alt="Not found" class="card-img">
                    <h2>{{a.title}}</h2>
                    <h4>Author:{{a.author}}</h4>
                    <div class="star-rating" data-rating="{{ a.star_given }}">
                        <span class="stars"></span>
                    </div>
                    <a href="{% url 'blogs:articles-detail' a.pk %}"><button>Read More</button></a>
                    <form action="{% url 'blogs:remove-watch-later' a.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="remove-button">Remove</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No article to watch later.</p>
    {% endif %}
{% endblock %}