conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('blogs/', include('blogs.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, UpdateProfileView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', UpdateProfileView.as_view(), name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Group,Permission
# Create your models here.


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_images/', blank=True, null=True, default='default_images/user_image.png')
    
    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_set',
        blank=True,
        help_text=(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        related_query_name='custom_user',
    )

    user_permissions = models.ManyToManyField(
        Permission,
        related_name='custom_user_set',
        blank=True,
        help_text='Specific permissions for this user.',
        related_query_name='custom_user',
    )

    class Meta:
        db_table = 'customuser'

    def __str__(self):
        return f'{self.username}'

users/forms.py
from django import forms
from users.models import CustomUser

class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'image', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'image')

users/views.py
from django.shortcuts import render,redirect
from .models import CustomUser
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserForm, ProfileUpdateForm
from django.contrib import messages
# Create your views here.

class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'users/register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            messages.success(request, 'Registration successful!')             
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            messages.error(request,'Something is wrong! \nTry again')
            return render(request, 'users/register.html', context=context)
        
class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'form': login_form
        }
        return render(request, 'users/login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You are now logged in') 
            return redirect('home:home_page')
        else:
            context = {
                'form': login_form
            }
            messages.error(request, 'Invalid username or password')
            return render(request, 'users/login.html', context=context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'You are now logged out')
        return redirect('home:home_page')

class ProfileView(LoginRequiredMixin,View):
    def get(self, request):
        return render(request, 'users/profile.html',{"user": request.user})
    
class UpdateProfileView(LoginRequiredMixin, View):
    def get(self, request):
        update_form = ProfileUpdateForm(instance=request.user)
        context = {
            'form': update_form
        }
        return render(request, 'users/update_profile.html', context=context)
    
    def post(self, request):
        update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            messages.success(request, 'Your profile has been updated!')
            return redirect('users:profile')
        else:
            context = {
                'form': update_form
            }
            return render(request, 'users/update_profile.html', context=context)

templates/users/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <div class="card-profile">
        {% if user.image %}
            <img src="{{ user.image.url }}" alt="User Image" height="150px">
        {% else %}
            <p>No image available</p>
        {% endif %}
        <h2>Username: {{ user.username }}</h2>
        <h3>Email: {{ user.email }}</h3>
        <h3>First Name: {{ user.first_name }}</h3>
        <h3>Last Name: {{ user.last_name }}</h3>

        <button>
            <a href=" url {% url 'users:edit_profile' %}">Edit Profile</a>           
        </button>
    </div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="content">
    <h1>Register</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
     </div>
{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block title %}Update Profile{% endblock %}

{% block context %}
  <h1>Update Profile</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}